classDiagram
    class Oficina{
      +Double estimativaTempo
      +Stack filaCarros
      +inserirCarro()
      +buscarCarro()
      +detalhesOficina()
    }
    class Carro{
      +String modelo
      +String fabricante
      +bool revisao
      +detalhesCarro()
    }